import Head from 'next/head'
import Image from 'next/image'

import Nav from "../components/Nav";
import Hero from "../components/Hero";
import AboutUs from "../components/AboutUs";
import Pricing from "../components/Pricing";
import Review from "../components/Review";
import Success from "../components/Success";
import CompanyLogos from "../components/CompanyLogos";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

import { Container, Card, Row, Text, Spacer, Button } from "@nextui-org/react";



export default function Home() {
    return (
        <div>
            <Head>
                <title>Carave</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Nav />
                <Container>
                    <Spacer y={1} />
                    <Hero />
                    <Spacer y={3} />
                    <hr />
                    <Spacer y={3} />
                    <AboutUs />
                    <Spacer y={3} />
                    <Pricing />
                    <Spacer y={3} />
                    <hr />
                    <Review />
                    <Spacer y={3} />
                    <hr />
                    <Success />
                    <Spacer y={3} />
                    <hr />
                    <Contact />
                    <Spacer y={3} />
                    <CompanyLogos />
                    <Spacer y={3} />
                    <Contact />
                    <Spacer y={3} />
                    <Footer />
                </Container>

            </main>
        </div>
    )
}
